spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${PGSQL_HOST:localhost}:5432/icpo_db_2
    username: ${DB_USERNAME}
  jpa:
    hibernate:
      ddl-auto: update #create-drop
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 10
